# To use:
# > brew tap homebrew/bundle
# > brew bundle

# Use GNU tools instead of the built-in ones
brew 'coreutils'
brew 'findutils'
brew 'gnu-sed'
brew 'gnu-tar'

# Easier extraction
brew 'atool'

# Shell
brew 'zsh'

# Editing
brew 'editorconfig'
brew 'emacs', args: ['with-cocoa', 'with-gnutls', 'with-librsvg']
brew 'git'
brew 'the_silver_searcher'

# Dotfile management
brew 'stow'